// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmhE_xT-ifhdzYAZMemC9Z1PQKG44pF4c',
    appId: '1:972293945607:web:f5ed20e70fa26a01b4eda2',
    messagingSenderId: '972293945607',
    projectId: 'car-rental-app-4870e',
    authDomain: 'car-rental-app-4870e.firebaseapp.com',
    storageBucket: 'car-rental-app-4870e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4z7qb7urqHe5tWtVTq95R2ZRdmg49ktE',
    appId: '1:972293945607:android:822403332a2a4957b4eda2',
    messagingSenderId: '972293945607',
    projectId: 'car-rental-app-4870e',
    storageBucket: 'car-rental-app-4870e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASDB6iq7_eL2TFYZc290EjdSVLYvjyBxI',
    appId: '1:972293945607:ios:a0bf850ec8f73e5bb4eda2',
    messagingSenderId: '972293945607',
    projectId: 'car-rental-app-4870e',
    storageBucket: 'car-rental-app-4870e.appspot.com',
    iosBundleId: 'com.example.carRentalApp',
  );

}